export const LOAD_MOVIES_START = 'LOAD_MOVIES_START';
export const LOAD_MOVIES_FAILED = 'LOAD_MOVIES_FAILED';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIE_INFO_START = 'LOAD_MOVIE_INFO_START';
export const LOAD_MOVIE_INFO_FAILED = 'LOAD_MOVIE_INFO_FAILED';
export const LOAD_MOVIE_INFO_SUCCESS = 'LOAD_MOVIE_INFO_SUCCESS';
